### ISSUE TITLE
IIFE and global space problem

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#12]
Read about IIFE and let's use it.

**Comment by odv** [comment]
@serge-nikitin I've researched IIFE and why this concept is useful but are they still needed in ES6 where we have let and const?

**Comment by serge-nikitin** [comment]
IIFE was actual before babel task. Now babel protect our app variables. I'll explain it in Skype.

**Comment by odv** [comment]
@serge-nikitin I noticed something weird in my code after adding my IIFE expression, more exactly, my onclick events no longer work but my addEventListener work fine. 

Should I convert my **onclick** lines to eventListeners? Also, how would I pass that *i* parameter if the answer to the previous question is yes.

**Comment by serge-nikitin** [comment]
I haven't checked it yet. But you should try to solve this problem yourself first. If eventListeners can solve it, do it.

You can try to use Function.prototype.bind if you have some problems with passing parameters.

**Comment by odv** [comment]
@serge-nikitin  Managed to fix it in the end.
