### ISSUE TITLE
Filters and ordering

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#13]
We need to add such functionality:

1) Filter todos: All / Completed / Non-completed
2) Ordering by create time. ASC / DESC

**Comment by odv** [comment]
@serge-nikitin I'm stuck here. Decided to start with item 2 in the list. 
Went on devdocs.io to research the sort method. Wrote a callback function to sort them by creation time but for some reason my view is not updating even though I call the displayTasks() function at the end.

What have I tried to debug this:

Took both sort methods with their callback and tested them in the chrome console. They return the desired output.

Not sure how to proceed now.

**Comment by serge-nikitin** [comment]
skip this task for a while. I'll tell you in Skype on Sunday how to work with filtering and sorting.

**Comment by odv** [comment]
Ok. Also noticed that localStorage is not updated when sortAsc and sortDes functions are called.
