### ISSUE TITLE
Split code into modules

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#18]
We should split our code into some modules. 
- main.js -- entry point and everything about rendering data
- store.js -- here we store our data and only in that module we modify our data. Also store.js should know nothing about HTML, DOM and rendering.

And now we need bundler. So it's time to add browserify.

**Comment by odv** [comment]
I'm stuck here because of this: https://github.com/eslint/eslint/issues/7764
I've tried: https://github.com/babel/babel-eslint

I keep getting: ParseError: 'import' and 'export' may appear only with 'sourceType: module' eventhough my .eslintrc has it.

At this stage I'm a bit lost because I really need that import statement in order to break the code into 2 separate files.

**Comment by odv** [comment]
One of the first issues I've encountered when trying to split my code into 2 distinct files is that my linter starts outputting a lot of errors if I do that. Really not sure how to fix that. I could use eslint-disable-next-line everywhere but that won't be professional.

**Comment by serge-nikitin** [comment]
have you uploaded such code? I don’t see any eslint errors now.

**Comment by odv** [comment]
I have forgot to add it. I've made a new branch using git-flow called 'feature-code-split' and added it here: https://github.com/jscraft-org/mentoring-project-2/blob/feature-code-split/src/js/state.js

**Comment by serge-nikitin** [comment]
you should learn about import/export sytnax of JS

i dont see any exports in state.js

**Comment by odv** [comment]
Yes, that was the issue.

**Comment by odv** [comment]
I've split my code but I don't understand why do I now get the following error: 
```Uncaught ReferenceError: tasksOutput is not defined```
*main.js: *https://github.com/jscraft-org/mentoring-project-2/blob/feature-code-split/src/js/main.js
*state.js: * https://github.com/jscraft-org/mentoring-project-2/blob/feature-code-split/src/js/state.js

**What have I tried:** I have tried to comment out lines 61 and 113 in my state.js that are causing the error just to see what happens next and I see that errors appear in other functions where I use dom variables like on line 5(state.js) addTask function.

**Comment by serge-nikitin** [comment]
your state.js:

```
function output() {
    tasksOutput.innerHTML = "";

    for (let task of todoItemsList) {
      let todoNote;
      let trashIcon;
      let editIcon;
      let checkmarkIcon;
      let taskName;
      let taskContainer;
      todoNote = document.createElement("li");

      trashIcon = document.createElement("i");
      editIcon = document.createElement("i");
      checkmarkIcon = document.createElement("i");

```

So the problem is here: tasksOutput.innerHTML = "";


But again. Your state.js should know about html, dom api NOTHING.

**Comment by serge-nikitin** [comment]
It looks like you still totally don't understand the main idea of code splitting.

In your state.js you have render() method. But state.js doesn't care about rendering / displaying data at all. 

state.js should only store and manipulate with data, but main.js should render data to browser.

So if you still don't understand this idea, let's skip this task at all. So you will have one file with all js code for this project.

**Comment by odv** [comment]
I've updated all my code.  *state.js* doesn't contain any DOM elements and all the rendering is handled in my *main.js* file. 
https://github.com/jscraft-org/mentoring-project-2/blob/feature-code-split/src/js/main.js
https://github.com/jscraft-org/mentoring-project-2/blob/feature-code-split/src/js/state.js

All the functionality of the previous stage where I had just one file is there and working without any errors.
