### ISSUE TITLE
npm scripts

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#21]
We need such npm scripts:
- npm run build -- must build (babel + browserify / webpack) our project, production ready
- npm run clean -- must clean all autogenerated code (bundle.js)
- npm start -- must run project for development. babel should watch for source files and update them automatically.

**Comment by odv** [comment]
Just added this commit in order to fix this issue. I'm linking it here because I forgot to add the issue number at the end so it won't be displayed here below our messages: https://github.com/jscraft-org/mentoring-project-2/commit/0414444c74ab42a41f43ef19d0ee42db7f7a5f0a
