### ISSUE TITLE
prettier

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#23]
You should't format code manually. 

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by odv** [comment]
I'm now using this extension for formatting. Also saw that after I've installed it, I was still using four spaces instead of 2. Also solved that issue. It seems that I forgot to install https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by serge-nikitin** [comment]
I used it before, but now this plugin is disabled in my edit because of one bug: https://github.com/editorconfig/editorconfig-vscode/issues/169

I don't know who exactly format code for me: just vscode of prettier. But I think they respect .editorconfig rules.

So I don't know what is the best solution. I personally haven't met any problems with .editorconfig file yet.
