### ISSUE TITLE
Make the pagination icons bigger

### ISSUE THREAD

**Issue by odv** [jscraft-org/mentoring-project-2#26]

**Comment by serge-nikitin** [comment]
And add some text for icons: Sort by name, time. Show all, show completed / uncompleted.

Now it's totally unclear what is going on when there are only icons. Need some text.

**Comment by odv** [comment]
@serge-nikitin  I've added tool-tips for everything so that when the user will hover they will see a short description of what that button does. I've also increased the font-size of the pagination elements and replaced those input buttons with material-icons.
