### ISSUE TITLE
Done status

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#5]
Let's add `done` status for our todo notes. So now we can:

- Add a new Todo
- Delete a Todo
- On / Off `done` status.

Also it's a good idea to add `id` field for our todo notes. So our store can looks like:

`[{id:1, done: false, createdAt: '2222-11-11....', note: 'Task 1'}, {id:2, done: true, createdAt: '2222-11-11....', note: 'Task 2'}]`

**Comment by odv** [comment]
@serge-nikitin I've constructed my task objects as you've mentioned above:
![task-structure](https://user-images.githubusercontent.com/5067625/30522582-56a4681e-9bdb-11e7-9e9d-38029ea64a0e.jpg)

Should I also focus on displaying and adding functionality for the task status here in this issue? Or I will take care of that once we get to the CSS styling phase.

**Comment by serge-nikitin** [comment]
This task is not complete. I can't set "done/undone" status to Todos.
Feel free to add CSS styling, just don't use any libraries like bootstrap.
Write your own CSS styles
