### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#6]
Let's use babel. We're going to use all new ES features. Let's use babel-preset-env.

**Comment by serge-nikitin** [comment]
Btw, for the first time let's make babel transpilation without gulp. It's useful skill to know hot to do it without any task runners / module bundlers - https://babeljs.io/docs/usage/cli

For many cases we can have a project without gulp. It's enough to have npm scripts.

**Comment by odv** [comment]
@serge-nikitin From what I've read, Babel allows you to use the newest JS language features in your browser by compiling it back to globally supported Javascript.

Since I'm already using **browserify**, wouldn't that cause any sort of conflicts with **Babel**?
Also, why should we use **babel**? Is it to support other browsers like IE, Opera, etc.?

**Comment by serge-nikitin** [comment]
We need babel to transpile modern ES6 code to ES5 (for old browsers support).

So with babel we should have something like this:

/src/main.js -- it's our source file
/app/scripts/script.js -- it will be a result of babel's transformation.
 So /app/scripts/script.js it will be a auto-generated code, so we should add this path to .gitignore

So, let's modernize our code. Prefer in your code arrow functions. 
 

BTW If you stuck with some issues feel free to take other issues. It's not so necessary to do it sequentially .

**Comment by serge-nikitin** [comment]
It's better to use common patterns for naming of directories

/src -- here we store all our source files. For this project it will be only one file
/src/main.js -- main js source file

And let's rename app to /public

So /public is the root directory for our http server.
So, this project should looks like this:

```

/public
/public/vendors/moment.js
/public/bundle.js -- we ignore this path in git
/public/css/styles.css
/index.html

/src/main.js
```
