### ISSUE TITLE
A bug with loop, var, and scope

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#9]
```
function displayTasks() {
    tasksOutput.innerHTML = '';
    for(var i = 0; i < tasks.length; i += 1) {
        let todoNote = document.createElement('li');
        todoNote.appendChild(document.createTextNode(tasks[i].note));
        todoNote.onclick = function(i) {
            deleteTask(i); 
        };
        tasksOutput.appendChild(todoNote);
    }
}
```

There is a classical bug with loop, var and scope. Try to find it, but anyway tomorrow we'll discuss it.

**Comment by serge-nikitin** [comment]
A hint: there are two bugs in this code :)

**Comment by odv** [comment]
@serge-nikitin I've replaced the **var** keyword in my for loop after the discussion we had on Skype. 
After some debugging and some time spent on MDM I understood what you said about events and that onclick not working correctly.

I was thinking about how I can rewrite that piece to work as intended. 
If I do something like this(note: function is not complete), will that be considered back practice?

```javascript
function displayTasks() {
let listNotes = '';

for(let i = 0; i < tasks.length; i += 1) {
    listNotes += '<li class="">';
    listNotes += tasks[i].taskName + '</li'>
}

document.querySelector("#task-output").innerHTML = listNotes;
}
```
That's the only lead I have so far. Using a variable, appending HTML tags to it and then use innerHTML to drop everything to the page.

**Comment by serge-nikitin** [comment]
This task is not complete. I can't still delete a Todo, it work wrong.
